# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."media-flaresolverr" = {
    image = "ghcr.io/flaresolverr/flaresolverr:latest";
    environment = {
      "CAPTCHA_SOLVER" = "none";
      "LOG_HTML" = "false";
      "LOG_LEVEL" = "info";
      "TZ" = "Australia/Sydney";
    };
    ports = [
      "8191:8191/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.6"
      "--network-alias=flaresolverr"
      "--network=media_media"
    ];
  };
  systemd.services."podman-media-flaresolverr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-media_media.service"
    ];
    requires = [
      "podman-network-media_media.service"
    ];
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };
  virtualisation.oci-containers.containers."media-jellyfin" = {
    image = "jellyfin/jellyfin";
    environment = {
      "JELLYFIN_PublishedServerUrl" = "https://jellyfin.7sref";
    };
    volumes = [
      "/media/media:/media:rw"
      "/data/jellyfin/cache:/cache:rw"
      "/data/jellyfin/config:/config:rw"
    ];
    ports = [
      "8096:8096/tcp"
    ];
    log-driver = "journald";
  };
  systemd.services."podman-media-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };
  virtualisation.oci-containers.containers."media-prowlarr" = {
    image = "ghcr.io/hotio/prowlarr";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Sydney/Australia";
    };
    volumes = [
      "/data/prowlarr:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.5"
      "--network-alias=prowlarr"
      "--network=media_media"
    ];
  };
  systemd.services."podman-media-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-media_media.service"
    ];
    requires = [
      "podman-network-media_media.service"
    ];
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };
  virtualisation.oci-containers.containers."media-qbittorrent" = {
    image = "ghcr.io/hotio/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Sydney/Australia";
      "WEBUI_PORTS" = "11090/tcp";
    };
    volumes = [
      "/media/torrents:/data/torrents:rw"
      "/data/qbittorrent:/config:rw"
    ];
    ports = [
      "11090:11090/tcp"
      "6882:6882/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.2"
      "--network-alias=qbittorrent"
      "--network=media_media"
    ];
  };
  systemd.services."podman-media-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-media_media.service"
    ];
    requires = [
      "podman-network-media_media.service"
    ];
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };
  virtualisation.oci-containers.containers."media-radarr" = {
    image = "ghcr.io/hotio/radarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Sydney/Australia";
    };
    volumes = [
      "/media:/data:rw"
      "/data/radarr:/config:rw"
    ];
    ports = [
      "7878:7878/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.4"
      "--network-alias=radarr"
      "--network=media_media"
    ];
  };
  systemd.services."podman-media-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-media_media.service"
    ];
    requires = [
      "podman-network-media_media.service"
    ];
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };
  virtualisation.oci-containers.containers."media-sonarr" = {
    image = "ghcr.io/hotio/sonarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Sydney/Australia";
    };
    volumes = [
      "/media:/data:rw"
      "/data/sonarr:/config:rw"
    ];
    ports = [
      "8989:8989/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.3"
      "--network-alias=sonarr"
      "--network=media_media"
    ];
  };
  systemd.services."podman-media-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-media_media.service"
    ];
    requires = [
      "podman-network-media_media.service"
    ];
    partOf = [
      "podman-compose-media-root.target"
    ];
    wantedBy = [
      "podman-compose-media-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-media_media" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f media_media";
    };
    script = ''
      podman network inspect media_media || podman network create media_media --subnet=172.21.0.0/16
    '';
    partOf = [ "podman-compose-media-root.target" ];
    wantedBy = [ "podman-compose-media-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-media-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
